### PR TITLE
expose sync status per repo via API

### LINKED ISSUE #29: Surface sync failures per repo
The background sync task logs pull failures to stdout, but there's no way for the frontend or API consumer to know which repos failed to sync. Should expose sync status per repo, e.g. last synced timestamp and last error, through the API.

### PR DESCRIPTION
**Pull request by Corium4**
Added last_synced_at and last_sync_error to the per-repo meta files and GET /repos response, both only appear when set. Successful sync saves the timestamp and clears any previous error, failed sync saves the error but keeps the old timestamp to indicate when the last successful clone happened. Clone also sets the time stamp upon completion, since that's technically the first sync. Passes clippy pedantic. 
Closes #29

### CODE REVIEW

File: backend/src/repo.rs [hunk 1]
```diff
@@ -106,13 +108,17 @@ pub fn list_repos(base_dir: &PathBuf) -> Result<Vec<RepoInfo>, AppError> {
...
+                    last_synced_at: meta.last_synced_at,
+                    last_sync_error: meta.last_sync_error,
                 });
             } else if path.join(".git").exists() {
                 seen.insert(name.to_string());
                 repos.push(RepoInfo {
                     name: name.to_string(),
                     path: path.to_string_lossy().to_string(),
                     status: RepoStatus::Ready,
+                    last_synced_at: None,
```
Comment (tfo-dot) [inline backend/src/repo.rs]: Wouldn't it be better to pick some arbitraty point in time (e.g. last commit) rather than Option::None?

File: backend/src/models.rs [hunk 2]
```diff
@@ -15,6 +15,10 @@ pub struct RepoMeta {
     pub token: Option<String>,
     #[serde(flatten)]
     pub status: RepoStatus,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub last_synced_at: Option<String>,
```
Comment (tfo-dot) [inline backend/src/models.rs]: Rather than string of RFC 3339, we should store timestamp in memory and (de)serialize as needed (saving to file / sending over network), also std::time exists

File: backend/src/models.rs [hunk 3]
```diff
@@ -23,6 +27,10 @@ pub struct RepoInfo {
     pub path: String,
     #[serde(flatten)]
     pub status: RepoStatus,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub last_synced_at: Option<String>,
```
Comment (tfo-dot) [inline backend/src/models.rs]: Same as https://github.com/tfo-dot/dockix/pull/31/changes/a18eb790aad2555d4aa4a75534b69ab7309db8a6#r3088175718

File: backend/src/models.rs [hunk 4]
```diff
@@ -15,6 +15,10 @@ pub struct RepoMeta {
     pub token: Option<String>,
     #[serde(flatten)]
     pub status: RepoStatus,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub last_synced_at: Option<String>,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub last_sync_error: Option<String>,
```
Comment (tfo-dot) [inline backend/src/models.rs]: Shouldn't this be merged into status field instead (within RepoStatus enum)?

**Review by tfo-dot — CHANGES_REQUESTED** [review]

File: backend/src/repo.rs (hunk 1 above)
Comment (Corium4) [reply backend/src/repo.rs]: Not sure if you mean this specific instance or the broader pattern of setting None. Either way, last commit time doesn't really answer "when was this fetched", since a repo with an old last commit cloned today should still show today. None feels the most accurate when we have no record of the actual fetch time. It gets replaced on the first sync cycle anyway. Also the highlighted case only happens when a meta file is missing, and even if we saved last commit time somewhere, it would probably live in the meta file, which doesn't help if it's gone.

File: backend/src/models.rs (hunk 2 above)
Comment (Corium4) [reply backend/src/models.rs]: Good point, will do.

File: backend/src/models.rs (hunk 3 above)
Comment (Corium4) [reply backend/src/models.rs]: Will do.

File: backend/src/models.rs (hunk 4 above)
Comment (Corium4) [reply backend/src/models.rs]: Sync status is conceptually different from repo status. Repo status answers "can I use this?" and sync fields answer "how fresh is it?". A Ready repo can have a sync error (stale but still usable), and sync history is meaningful regardless of current status. Merging would combine two independent things. Can change it if you want, your call.
