### PR TITLE
Fix/clone blocking

### LINKED ISSUE #28: Clone blocks server and times out on large repos
Currently the clone endpoint blocks until the full repo is downloaded and other endpoints become unresponsive during the download. For large repos this can take minutes and the client may time out. Should either return immediately with a 'cloning in progress' status and let it finish in the background, or add a configurable timeout.

### PR DESCRIPTION
**Pull request by Corium4**
Cloning large repos used to block the entire server until the download finished. Other endpoints like /repos and /analyze became unresponsive too, and the client would eventually time out. The repo would still end up on disk after a while but with no feedback to the user.
Clone endpoint now returns 202 immediately and runs the download in the background. Status is tracked per repo through GET /repos which reports "cloning", "ready" or "failed" with an error message if something went wrong. State is stored as marker files in the repositories directory so it survives restarts. On startup the server detects and cleans up any clones that were interrupted by a crash, marking them as failed so they can be retried.
Clones default to shallow (depth 1) since Dockix only needs the latest code for parsing, not git history. Depth is configurable through an optional field in the request body. 
Failed clones can be retried by sending the same clone request again, the old attempt gets cleaned up automatically. Sync skips repos that are still cloning or have failed. Git errors like wrong tokens or bad URLs now show friendlier messages instead of raw git2 internals.
Passes clippy pedantic.
Depends on #27 , merge that first.
Closes #28

### CODE REVIEW

File: backend/src/models.rs [hunk 1]
```diff
@@ -5,13 +5,17 @@ use std::path::PathBuf;
 pub struct RepoInfo {
     pub name: String,
     pub path: String,
+    pub status: String,
```
Comment (tfo-dot) [inline backend/src/models.rs]: Use enum instead of string, we can provide the state directly instead of adding error field when it fails

File: backend/src/repo.rs [hunk 2]
```diff
@@ -37,48 +38,143 @@ pub fn load_token(repo_path: &Path) -> Option<String> {
...
-        None => {
-            Repository::clone(url, target_path)?;
-        }
+    let token_owned = token.map(String::from);
+    if let Some(ref token) = token_owned {
+        let token = token.clone();
+        callbacks.credentials(move |_url, _username, _allowed| {
+            git2::Cred::userpass_plaintext("x-access-token", &token)
+        });
     }
```
Comment (tfo-dot) [inline backend/src/repo.rs]: Wouldn't is be simpler to just use the code below instead?
```rust
    if let Some(token) = token {
        callbacks.credentials(move |_url, _username, _allowed| {
            git2::Cred::userpass_plaintext("x-access-token", token)
        });
    }
```

File: backend/src/errors.rs
Comment (tfo-dot) [inline backend/src/errors.rs:14]: Is there a need to have a message? When these structs are used, the generic message is used anyway like `Repository not found, check the URL.`, these addidtional messages can be removed (or factored into it's own error type) for all the non specific (internal / git messages should stay because we want to know what really went wrong)

File: backend/src/repo.rs [hunk 3]
```diff
@@ -1,13 +1,14 @@
 use std::fs;
 use std::path::{Path, PathBuf};
 use walkdir::WalkDir;
-use git2::Repository;
 
 use crate::errors::AppError;
 use crate::models::{RepoInfo, ParsedRepo};
 use crate::parsers::get_parser_for_extension;
 
 const TOKEN_FILE: &str = ".dockix-token";
```
Comment (tfo-dot) [inline backend/src/repo.rs]: Wouldn't it be better to store all the data inside one file like `info.json`? It would help with other things like tracking last sync of the repo and such.

**Review by tfo-dot — CHANGES_REQUESTED** [review]

**Review by tfo-dot — APPROVED** [review]
